/* Generated By:JJTree&JavaCC: Do not edit this line. JmmConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JmmConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IMPORT = 5;
  /** RegularExpression Id. */
  int CLASS = 6;
  /** RegularExpression Id. */
  int EXTENDS = 7;
  /** RegularExpression Id. */
  int PUBLIC = 8;
  /** RegularExpression Id. */
  int RETURN = 9;
  /** RegularExpression Id. */
  int STATIC = 10;
  /** RegularExpression Id. */
  int VOID = 11;
  /** RegularExpression Id. */
  int MAIN = 12;
  /** RegularExpression Id. */
  int STRING = 13;
  /** RegularExpression Id. */
  int INT = 14;
  /** RegularExpression Id. */
  int BOOLEAN = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int LENGTH = 19;
  /** RegularExpression Id. */
  int TRUE_ = 20;
  /** RegularExpression Id. */
  int FALSE_ = 21;
  /** RegularExpression Id. */
  int THIS = 22;
  /** RegularExpression Id. */
  int NEW = 23;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 24;
  /** RegularExpression Id. */
  int DECIMAL = 25;
  /** RegularExpression Id. */
  int HEXADECIMAL = 26;
  /** RegularExpression Id. */
  int BINARY = 27;
  /** RegularExpression Id. */
  int OCTAL = 28;
  /** RegularExpression Id. */
  int IDENTIFIER = 29;
  /** RegularExpression Id. */
  int LETTER = 30;
  /** RegularExpression Id. */
  int DIGIT = 31;
  /** RegularExpression Id. */
  int SEMICOLON = 32;
  /** RegularExpression Id. */
  int COLON = 33;
  /** RegularExpression Id. */
  int LEFT_BRACE = 34;
  /** RegularExpression Id. */
  int RIGHT_BRACE = 35;
  /** RegularExpression Id. */
  int LEFT_BRACKET = 36;
  /** RegularExpression Id. */
  int RIGHT_BRACKET = 37;
  /** RegularExpression Id. */
  int LEFT_PARENTESIS = 38;
  /** RegularExpression Id. */
  int RIGHT_PARENTESIS = 39;
  /** RegularExpression Id. */
  int DOT = 40;
  /** RegularExpression Id. */
  int SUM = 41;
  /** RegularExpression Id. */
  int SUB = 42;
  /** RegularExpression Id. */
  int MUL = 43;
  /** RegularExpression Id. */
  int DIV = 44;
  /** RegularExpression Id. */
  int LESS_THAN = 45;
  /** RegularExpression Id. */
  int AND = 46;
  /** RegularExpression Id. */
  int NEGATION = 47;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"import\"",
    "\"class\"",
    "\"extends\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"String\"",
    "\"int\"",
    "\"boolean\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"length\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"new\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL>",
    "<HEXADECIMAL>",
    "<BINARY>",
    "<OCTAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\";\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\"&&\"",
    "\"!\"",
  };

}
