/* Generated By:JavaCC: Do not edit this line. JmmTreeConstants.java Version 5.0 */
public interface JmmTreeConstants
{
  public int JJTPARSEEXPRESSION = 0;
  public int JJTCLASSDECLARATION = 1;
  public int JJTVARDECLARATION = 2;
  public int JJTTYPE = 3;
  public int JJTMETHODDECLARATION = 4;
  public int JJTSTATEMENT = 5;
  public int JJTVOID = 6;
  public int JJTAND = 7;
  public int JJTLESSTHAN = 8;
  public int JJTSUM = 9;
  public int JJTMUL = 10;
  public int JJTRESTOFEXPRESSION = 11;


  public String[] jjtNodeName = {
    "ParseExpression",
    "ClassDeclaration",
    "VarDeclaration",
    "Type",
    "MethodDeclaration",
    "Statement",
    "void",
    "AND",
    "LESSTHAN",
    "SUM",
    "MUL",
    "RestOfExpression",
  };
}
/* JavaCC - OriginalChecksum=312616704707f40fb33c40da8865a456 (do not edit this line) */
