/* Generated By:JavaCC: Do not edit this line. JmmTreeConstants.java Version 5.0 */
public interface JmmTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTCLASSDECLARATION = 1;
  public int JJTVARDECLARATION = 2;
  public int JJTTYPE = 3;
  public int JJTMETHODDECLARATION = 4;
  public int JJTSTATEMENT = 5;


  public String[] jjtNodeName = {
    "Expression",
    "ClassDeclaration",
    "VarDeclaration",
    "Type",
    "MethodDeclaration",
    "Statement",
  };
}
/* JavaCC - OriginalChecksum=093c456f95c01a47a3f7227c47b4bc7e (do not edit this line) */
